export const jokesCategories = [
  {
    id: 'friendly',
    title: require('../assets/images/FriendlyBull.png'),
    description: 'Good, light, universal jokes',
    image: require('../assets/images/friendly_bull.png'),
    jokes: [
      "I'm not fat - I'm just a bull with a big soul.",
      'Smile, even if the horns are not symmetrical.',
      "I'm not stubborn - I'm stable in decisions.",
      'If the day is bad, then tomorrow there will be milk and honey.',
      "I'm not late - I came at my own pace.",
      'A bull without a mood is just a cow without coffee.',
      "I'm for peace... but the line at the store is an exception.",
      "If you don't know what to do - chew grass and think.",
      'Life is short. Eat another bun.',
      "I'm not lazy - I'm energy-saving.",
      'Not all heroes wear capes. Some wear hooves.',
      "I'm not rude - I'm just straight as a horn.",
      'A smile is when even a bull looks cute.',
      "If something doesn't work out - move on.",
      "I'm not arguing, I'm just right.",
      'A good bull is a happy bull.',
      'Even a bull sometimes wants a hug.',
      'A day without a joke is like a field without grass.',
      "Don't take it to heart. Take it closer to your stomach.",
      'Everything will be fine. I checked.',
    ],
  },

  {
    id: 'savage',
    title: require('../assets/images/SavageBull.png'),
    description: 'Harsh, with jokes, but without toxicity',
    image: require('../assets/images/savage_bull.png'),
    jokes: [
      "I'm not angry - it's just that the truth hurts.",
      "Your joke was so weak that even I didn't get angry.",
      "I've seen grass funnier than this.",
      'If it was a joke - call witnesses.',
      'Did you want laughter? Silence came out.',
      "I'm not criticizing - I'm saving humor.",
      'Even my tail laughs more.',
      'It was brave. And in vain.',
      'A joke without a punchline is like a bull without horns.',
      'I would laugh… but no.',
      'This is not a failure. This is training.',
      "It hurts me to watch, but I'm watching.",
      'Next joke, please. This one is already dead.',
      "If humor is a weapon, you're shooting blanks.",
      "I'm not angry. I'm disappointed.",
      'Was that a joke or a test of patience?',
      "I've heard better. From a cow.",
      "Let's do it again. You have potential. Somewhere.",
      'I giggled. Inside. Not for long.',
      'Minus not for the joke. For the effort.',
    ],
  },

  {
    id: 'smart',
    title: require('../assets/images/SmartBull.png'),
    description: 'Smart, ironic, a little sarcastic',
    image: require('../assets/images/smart_bull.png'),
    jokes: [
      "It was a joke with subtext. Too bad there's no text.",
      'I laugh logically.',
      "Humor is mathematics. It didn't work out here.",
      'This joke needs an explanation. So no.',
      "If you think about it… it's better not to.",
      'It was interesting. Not funny, but interesting.',
      'I appreciated the idea. The implementation escaped.',
      'Subtle. So much so that it broke.',
      'A joke with potential. The potential is gone.',
      'I would smile, but the analysis forbids it.',
      'This is humor for a narrow circle. A very narrow one.',
      'I understood the joke. I would like not to understand.',
      'It was intellectual. Almost.',
      'The idea is good. The context is not.',
      'Funny from a theoretical point of view.',
      'I am not laughing, I am fixing.',
      'There was a joke here. Somewhere between the words.',
      'This is not a joke. This is an attempt.',
      'I appreciated the structure. The content is questionable.',
      'There is an idea. There is no laughter.',
    ],
  },
];
